const cards = {
  "OGN-001": "Blazing Scorcher",
  "OGN-002": "Brazen Buccaneer",
  "OGN-003": "Chemtech Enforcer",
  "OGN-004": "Cleave",
  "OGN-005": "Disintegrate",
  "OGN-006": "Flame Chompers",
  "OGN-007": "Fury Rune",
  "OGN-008": "Get Excited!",
  //"OGN-009": "Nombre",
  "OGN-010": "Legion Rearguard",
  "OGN-011": "Magma Wurm",
  "OGN-012": "Noxus Hopeful",
  "OGN-013": "Pouty Poro",
  "OGN-014": "Sky Splitter",
  "OGN-015": "Captain Farron",
  "OGN-016": "Dangerous Duo",
  //"OGN-017": "Nombre",
  //"OGN-018": "Nombre",
  //"OGN-019": "Nombre",
  "OGN-020": "Scrapyard Champion",
  //"OGN-": "Nombre",
  //"OGN-": "Nombre",
  //"OGN-": "Nombre",
  "OGN-024": "Void Seeker",
  //"OGN-": "Nombre",
  //"OGN-": "Nombre",
  "OGN-027": "Darius, Trifarian",
  "OGN-028": "Draven, Showboat",
  "OGN-029": "Falling Star",
  "OGN-030": "Jinx, Demolitionist",
  //"OGN-": "Nombre",
  //"OGN-": "Nombre",
  //"OGN-": "Nombre",
  "OGN-034": "Tryndamere, Barbarian",
  "OGN-035": "Vayne, Hunter",
  "OGN-036": "Vi, Destructive",
  "OGN-037": "Immortal Phoenix",
  "OGN-038": "Kadregrin the Infernal",
  //"OGN-": "Nombre",
  "OGN-040": "Seal of Rage",
  "OGN-041": "Volibear, Furious",
  "OGN-042": "Calm Rune",
  "OGN-043": "Charm",
  "OGN-044": "Clockwork Keeper",
  "OGN-045": "Defy",
  "OGN-046": "En Garde",
  "OGN-047": "Find Your Center",
  "OGN-048": "Meditation",
  "OGN-049": "Playful Phantom",
  "OGN-050": "Rune Prison",
  //"OGN-": "Nombre",
  "OGN-052": "Stalwart Poro",
  "OGN-053": "Stand United",
  //"OGN-": "Nombre",
  "OGN-055": "Wielder of Water",
  "OGN-056": "Adaptatron",
  "OGN-057": "Block",
  "OGN-058": "Discipline",
  "OGN-059": "Eclipse Herald",
  //"OGN-060": "Nombre",
  "OGN-061": "Poro Herder",
  //"OGN-062": "Nombre",
  "OGN-063": "Spirit's Refuge",
  "OGN-064": "Wind Wall",
  //"OGN-": "Nombre",
  "OGN-066": "Ahri, Alluring",
  "OGN-067": "Caitlyn, Patrolling",
  "OGN-068": "Caitlyn, Patrolling",
  "OGN-069": "Last Stand",
  //"OGN-": "Nombre",
  //"OGN-": "Nombre",
  //"OGN-": "Nombre",
  "OGN-073": "Sona, Harmonious",
  "OGN-074": "Taric, Protector",
  //"OGN-": "Nombre",
  "OGN-076": "Yasuo, Remorseful",
  "OGN-077": "Zhonya's Hourglass",
  "OGN-078": "Lee Sin, Ascetic",
  "OGN-079": "Leona, Zealot",
  //"OGN-": "Nombre",
  "OGN-081": "Seal of Focus",
  "OGN-082": "Whiteflame Protector",
  "OGN-083": "Consult the Past",
  "OGN-084": "Eager Apprentice",
  "OGN-085": "Falling Comet",
  //"OGN-": "Nombre",
  "OGN-087": "Lecturing Yordle",
  "OGN-088": "Mega-Mech",
  "OGN-089": "Mind Rune",
  //"OGN-": "Nombre",
  //"OGN-": "Nombre",
  //"OGN-": "Nombre",
  //"OGN-": "Nombre",
  //"OGN-": "Nombre",
  "OGN-094": "Sprite Call",
  "OGN-095": "Stupefy",
  "OGN-096": "Watchful Sentry",
  "OGN-097": "Blastcone Fae",
  //"OGN-": "Nombre",
  "OGN-099": "Garbage Grabber",
  "OGN-100": "Gemcraft Seer",
  "OGN-101": "Mushroom Pouch",
  "OGN-102": "Portal Rescue",
  "OGN-103": "Ravenbloom Student",
  //"OGN-": "Nombre",
  "OGN-105": "Singularity",
  //"OGN-106": "Nombre",
  //"OGN-107": "Nombre",
  "OGN-108": "Ava Achiever",
  "OGN-109": "Dr. Mundo, Expert",
  "OGN-110": "Ekko, Recurrent",
  "OGN-111": "Heimerdinger, Inventor",
  "OGN-112": "Kai'Sa, Evolutionary",
  "OGN-113": "Malzahar, Fanatic",
  "OGN-114": "Progress Day",
  "OGN-115": "Promising Future",
  //"OGN-": "Nombre",
  "OGN-117": "Viktor, Innovator",
  "OGN-118": "Wraith of Echoes",
  "OGN-119": "Ahri, Inquisitive",
  "OGN-120": "Seal of Insight",
  "OGN-121": "Teemo, Strategist",
  "OGN-123": "Unchecked Power",
  "OGN-124": "Arena Bar",
  "OGN-125": "Bilgewater Bully",
  "OGN-126": "Body Rune",
  "OGN-127": "Cannon Barrage",
  "OGN-128": "Challenge",
  "OGN-129": "Confront",
  "OGN-130": "Crackshot Corsair",
  "OGN-131": "Dune Drake",
  "OGN-132": "First Mate",
  "OGN-133": "Flurry of Blades",
  "OGN-134": "Mobilize",
  "OGN-136": "Pit Rookie",
  "OGN-137": "Stormclaw Ursine",
  "OGN-138": "Catalyst of Aeons",
  "OGN-139": "Cithria of Cloudfield",
  "OGN-140": "Herald of Scales",
  "OGN-142": "Mountain Drake",
  "OGN-147": "Wildclaw Shaman",
  "OGN-148": "Anivia, Primal",
  "OGN-149": "Carnivorous Snapvine",
  "OGN-150": "Kraken Hunter",
  "OGN-152": "Mistfall",
  "OGN-153": "Overt Operation",
  "OGN-154": "Primal Strength",
  "OGN-155": "Qiyana, Victorious",
  "OGN-157": "Udyr, Wildman",
  "OGN-158": "Volibear, Imposing",
  "OGN-159": "Warwick, Hunter",
  "OGN-160": "Dazzling Aurora",
  "OGN-161": "Deadbloom Predator",
  "OGN-162": "Miss Fortune, Captain",
  "OGN-163": "Seal of Strength",
  "OGN-164": "Sett, Brawler",
  "OGN-165": "Cemetery Attendant",
  "OGN-166": "Chaos Rune",
  "OGN-168": "Fight or Flight",
  "OGN-169": "Gust",
  "OGN-170": "Morbid Return",
  "OGN-171": "Mystic Poro",
  "OGN-172": "Rebuke",
  "OGN-174": "Sai Scout",
  "OGN-176": "Sneaky Deckhand",
  "OGN-177": "Stealthy Pursuer",
  "OGN-178": "Undercover Agent",
  "OGN-179": "Acceptable Losses",
  "OGN-181": "Pack of Wonders",
  "OGN-185": "Traveling Merchant",
  "OGN-187": "Whirlwind",
  "OGN-189": "Kayn, Unleashed",
  "OGN-190": "Kog'maw, Caustic",
  "OGN-191": "Maddened Marauder",
  "OGN-193": "Miss Fortune, Buccaneer",
  "OGN-194": "Nocturne, Horrifying",
  "OGN-197": "Teemo, Scout",
  "OGN-200": "Twisted Fate, Gambler",
  "OGN-201": "Invert Timelines",
  "OGN-202": "Jinx, Rebel",
  "OGN-203": "Possession",
  "OGN-204": "Seal of Discord",
  "OGN-205": "Yasuo, Windrider",
  "OGN-206": "Back to Back",
  "OGN-207": "Call to Glory",
  "OGN-208": "Cruel Patron",
  "OGN-209": "Cull the Weak",
  "OGN-210": "Daring Poro",
  "OGN-211": "Faithful Manufactor",
  "OGN-212": "Forge of the Future",
  "OGN-213": "Hidden Blade",
  "OGN-214": "Order Rune",
  "OGN-215": "Petty Officer",
  "OGN-216": "Soaring Scout",
  "OGN-217": "Trifarian Gloryseeker",
  "OGN-218": "Vanguard Captain",
  "OGN-219": "Vanguard Sergeant",
  "OGN-222": "Noxian Drummer",
  "OGN-225": "Solari Chief",
  "OGN-230": "Albus Ferros",
  "OGN-232": "Fiora, Victorious",
  "OGN-233": "Grand Strategem",
  "OGN-234": "Harnessed Dragon",
  "OGN-235": "Karma, Channeler",
  "OGN-238": "Leona, Determined",
  "OGN-239": "Machine Evangel",
  "OGN-240": "Sett, Kingpin",
  "OGN-241": "Shen, Kinkou",
  "OGN-243": "Darius, Executioner",
  "OGN-243": "Divine Judgment",
  "OGN-245": "Seal of Unity",
  "OGN-246": "Viktor, Leader",
  "OGN-247": "Kai'Sa, Daughter of the Void",
  "OGN-248": "Icathian Rain",
  "OGN-249": "Volibear, Relentless Storm",
  "OGN-250": "Stormbringer",
  "OGN-251": "Jinx, Loose Cannon",
  "OGN-252": "Super Mega Death Rocket!",
  "OGN-253": "Darius, Hand of Noxus",
  "OGN-254": "Noxian Guillotine",
  "OGN-255": "Ahri, Nine-Tailed Fox",
  "OGN-256": "Fox-Fire",
  "OGN-257": "Lee Sin, Blind Monk",
  "OGN-258": "Dragon's Rage",
  "OGN-259": "Yasuo, Unforgiven",
  "OGN-260": "Last Breath",
  "OGN-261": "Leona, Radiant Dawn",
  "OGN-262": "Zenith Blade",
  "OGN-263": "Teemo, Swift Scout",
  "OGN-264": "Guerilla Warfare",
  "OGN-265": "Viktor, Herald of the Arcane",
  "OGN-266": "Siphon Power",
  "OGN-267": "Miss Fortune, Bounty Hunter",
  "OGN-268": "Bullet Time",
  "OGN-269": "Sett, The Boss",
  "OGN-270": "Showstopper",
  "OGN-273": "Recruit",
  "OGN-275": "Altar to Unity",
  "OGN-276": "Aspirant's Climb",
  "OGN-277": "Back-Alley Bar",
  "OGN-278": "Bandle Tree",
  "OGN-279": "Fortified Position",
  "OGN-284": "Obelisk of Power",
  "OGN-285": "Reaver's Row",
  "OGN-286": "Reckoner's Arena",
  "OGN-287": "Sigil of the Storm",
  "OGN-288": "Startipped Peak",
  "OGN-289": "Targon's Peak",
  "OGN-290": "The Arena's Greatest",
  "OGN-291": "The Candlelit Sanctum",
  "OGN-292": "The Dreaming Tree",
  "OGN-293": "The Grand Plaza",
  "OGN-294": "Trifarian War Camp",
  "OGN-296": "Void Gate",
  "OGN-297": "Windswept Hillock",
  "OGN-298": "Zaun Warrens",
  "OGS-001": "Annie, Fiery",
  "OGS-002": "Firestorm",
  "OGS-003": "Incinerate",
  "OGS-004": "Master Yi, Meditative",
  "OGS-005": "Zephyr Sage",
  "OGS-006": "Lux, Illuminated",
  "OGS-007": "Garen, Rugged",
  "OGS-008": "Gentlemen's Duel",
  "OGS-009": "Master Yi, Honed",
  "OGS-010": "Annie, Stubborn",
  "OGS-011": "Flash",
  "OGS-012": "Blast of Power",
  "OGS-013": "Garen, Commander",
  "OGS-014": "Lux, Crownguard",
  "OGS-015": "Recruit the Vanguard",
  "OGS-016": "Vanguard Attendant",
  "OGS-017": "Annie, Dark Child",
  "OGS-018": "Tibbers",
  "OGS-019": "Master Yi, Wuju Bladesman",
  "OGS-020": "Highlander",
  "OGS-021": "Lux, Lady of Luminosity",
  "OGS-022": "Final Spark",
  "OGS-023": "Garen, Might of Demacia",
  "OGS-024": "Decisive Strike",
};

module.exports = cards;
